dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views 
# from dogs.views import DogList

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.DogList.as_view(), name='index'),
    path('dogs/<int:dog_id>', views.dogs_detail, name="detail"),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_naps/', views.add_naps, name='add_naps'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('dogs/<int:dog_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
]

main_app/models.py
from django.db import models
from django.urls import reverse


NAPS = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening')
)


class Toy(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('toys_detail', kwargs={'pk': self.id})


class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return f"{self.name} - {self.age}"
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'dog_id': self.id})


class Naps(models.Model):
    date = models.DateField("nap date")
    nap = models.CharField(max_length=1, choices=NAPS, default=NAPS[0][0])
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_nap_display()} on {self.date} for {self.dog}"

main_app/forms.py
from django.forms import ModelForm
from .models import Naps

class NapsForm(ModelForm):
  class Meta:
    model = Naps
    fields = ['date', 'nap']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Dog, Toy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import NapsForm


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

class DogList(ListView):
    model = Dog
    template_name = 'dogs/index.html'

class DogCreate(CreateView):
    model = Dog
    fields = '__all__'
    success_url = '/dogs/'

class DogUpdate(UpdateView):
  model = Dog
  fields = ['name', 'breed', 'age']

class DogDelete(DeleteView):
  model = Dog
  success_url = '/dogs/'

def dogs_detail(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    id_list = dog.toys.all().values_list('id')
    toys_dog_doesnt_have = Toy.objects.exclude(id__in=id_list)
    naps_form = NapsForm()
    return render(request, 'dogs/detail.html', {'dog': dog, 'naps_form': naps_form, 'toys': toys_dog_doesnt_have })

def add_naps(request, dog_id):
  form = NapsForm(request.POST)
  if form.is_valid():
    new_naps = form.save(commit=False)
    new_naps.dog_id = dog_id
    new_naps.save()
    return redirect('detail', dog_id=dog_id)

class ToyList(ListView):
  model = Toy

class ToyDetail(DetailView):
  model = Toy

class ToyCreate(CreateView):
  model = Toy
  fields = '__all__'

class ToyUpdate(UpdateView):
  model = Toy
  fields = ['name', 'color']

class ToyDelete(DeleteView):
  model = Toy
  success_url = '/toys/'


def assoc_toy(request, dog_id, toy_id):
  Dog.objects.get(id=dog_id).toys.add(toy_id)
  return redirect('detail', dog_id=dog_id)


class DogCreate(CreateView):
  model = Dog
  fields = ['name', 'breed', 'age']

main_app/templates/about.html
{% extends 'base.html' %}
{% block content  %}
<h1>About the Dog Collector</h1>
<hr /> 
<p>Hire the Dog Collector<p>
{% endblock  %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dog Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  <link
    rel="stylesheet" 
    type="text/css" 
    href="{% static 'css/style.css' %}" />
    

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper green">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;DogCollector</a></li>
        </ul>
        <ul class="right">
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'dogs_create' %}">Add a Dog</a></li>
            <li><a href="{% url 'index' %}">View All Dogs</a></li>
            <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
            <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer green">
    <div class="center">All Rights Reserved, &copy; 2022 Dog Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description|linebreaks }}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dogs_update' dog.id %}">Edit</a>
        <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <div class="col s6">
       
        <form action="{% url 'add_naps' dog.id %}" method="POST">
          {% csrf_token %}
          {{ naps_form.as_p }}
          <input type="submit" class="btn" value="Add Feeding">
        </form>
      
        <table class="striped">
        
      
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Nap</th></tr>
      </thead>
      <tbody>
        {% for naps in dog.naps_set.all %}
          <tr>
            <td>{{naps.date}}</td>
            <td>{{naps.get_nap_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ dog.name }}'s Toys</h3>
    {% if dog.toys.count %}
      {% for toy in dog.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
            A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>Needs Love!</h5>
    {% endif %}
  </div>
</div>
<div class="col s6">
    <h3>Toy Chest</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
            A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' dog.id toy.id %}" method="POST">
                {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{dog.name}}'s Spoiled!</h5>
    {% endif %}
  </div>
  

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

    const selectEl = document.getElementById('id_nap');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>

{% for dog in object_list  %}
<div class="card">
    <a href="{% url 'detail' dog.id %}">
    <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
      <p>Breed: {{ dog.breed }}</p>
      {% if dog.age > 0 %}
        <p>Age: {{ dog.age }}</p>
      {% else %}
        <p>Age: Puppy</p>
      {% endif %}

    </div>
    </a>
</div>

{% endfor %}

{% endblock  %}

main_app/templates/home.html
{% extends 'base.html' %}{% block content  %}

<h1>Welcome</h1>

{% endblock  %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dog</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
  <h1>Add Dog</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}